### ISSUE TITLE
Complete TTTEngine Implementation and Fix Related TODOs / FIXMEs

### ISSUE THREAD

**Issue by nikitadurasov** [nikitadurasov/torch-ttt#1]
### Description
The `TTTEngine` implementation is incomplete, and there are several `TODO` and `FIXME` comments that need to be resolved. This issue aims to:
- Finish the implementation of `TTTEngine`.
- Address all `TODO` and `FIXME` comments in the module.

### Relevant File
[ttt_engine.py](https://github.com/nikitadurasov/torch-ttt/blob/main/torch_ttt/engine/ttt_engine.py)

#### Tasks

- [x] Add CUDA support to the class [TODO](https://github.com/nikitadurasov/torch-ttt/blob/b1c27c2196c1dd35b7e6776d076ef6ea26e67368/torch_ttt/engine/ttt_engine.py#L6)
- [x] Properly rotate image during inference [FIXME](https://github.com/nikitadurasov/torch-ttt/blob/b1c27c2196c1dd35b7e6776d076ef6ea26e67368/torch_ttt/engine/ttt_engine.py#L37)
- [x] Implement the angel_head for 3D case [TODO](https://github.com/nikitadurasov/torch-ttt/blob/b1c27c2196c1dd35b7e6776d076ef6ea26e67368/torch_ttt/engine/ttt_engine.py#L96)

---
### Priority
High
